server:
  port: 8083
  
spring: 
 application:
  name: user-meta-data 

 data:
  mongodb:
   uri: mongodb://localhost:27017/usermicroservice
   database: usermicroservice  

logging:
 level:
  root: INFO
   com.casestudy=TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
 
  instance:
    hostname: localhost