server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-meta-data
          uri: lb://user-meta-data
          predicates:
            - Path=/offerzone/users/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: USER-SERVICE
#                fallbackuri: forward:/userServiceFallBack
                
        - id: add-to-cart
          uri: lb://add-to-cart
          predicates:
            - Path=/offerzone/addToCart/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name:  ADD-TO-CART-SERVICE
#                fallbackuri: forward:/addToCartServiceFallBack
                
        - id: product-details
          uri: lb://product-details
          predicates:
            - Path=/offerzone/products/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name:  PRODUCT-DETAILS-SERVICE
#                fallbackuri: forward:/productDetailsServiceFallBack  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost